// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace simplicode
{
    internal sealed partial class Vsix
    {
        public const string Id = "simplicode.736d277e-630b-45f2-a011-d8dfde76bb73";
        public const string Name = "simplicode";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "지섭 김";
        public const string Tags = "";
    }
}
